=== dizheng/EL/ltf.v1.5.dtd
<!--
			      A DTD for
	           LDC LCTL Tokenized Text XML Files

		      Linguistic Data Consortium
			    August 15, 2006

			     Version 1.1
-->

<!ELEMENT LCTL_TEXT (DOC+)                         >
<!ATTLIST LCTL_TEXT lang CDATA         #IMPLIED   
                    source_file CDATA  #IMPLIED   
                    source_type CDATA  #IMPLIED   
                    author CDATA       #IMPLIED   
                    encoding CDATA     #IMPLIED    >

<!ELEMENT DOC (HEADLINE|DATELINE|AUTHORLINE|TEXT)+ >
<!ATTLIST DOC id           ID     #REQUIRED
              tokenization CDATA  #IMPLIED
              grammar      CDATA  #IMPLIED
              raw_text_char_length  CDATA #IMPLIED
              raw_text_md5          CDATA #IMPLIED
>

<!ELEMENT HEADLINE (SEG+)                          >
<!ELEMENT DATELINE (#PCDATA)                       >
<!ELEMENT AUTHORLINE (#PCDATA)                     >
<!ELEMENT TEXT (P|SEG)+                            >

<!ELEMENT P (SEG+)                                 >

<!ELEMENT SEG (ORIGINAL_TEXT?, TOKEN*)             >
<!ATTLIST SEG id             ID     #REQUIRED            
              start_token    IDREF  #IMPLIED
              end_token      IDREF  #IMPLIED
	      start_char     CDATA  #IMPLIED
	      end_char       CDATA  #IMPLIED        
>

<!ELEMENT ORIGINAL_TEXT (#PCDATA)                  >

<!ELEMENT TOKEN (#PCDATA)                          >
<!ATTLIST TOKEN id           ID     #REQUIRED            
                attach       (LEFT|RIGHT|BOTH) 
			            #IMPLIED            
		pos          CDATA  #IMPLIED            
		morph        CDATA  #IMPLIED            	
		gloss        CDATA  #IMPLIED            	
		start_char   CDATA  #IMPLIED
		end_char     CDATA  #IMPLIED        
>

=== dizheng/EL/data/test/data/eng/newswire/ENG_NW_001424_20150208_F0010006C.nw.ltf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LCTL_TEXT SYSTEM "ltf.v1.5.dtd">
<LCTL_TEXT>
<DOC id="ENG_NW_001424_20150208_F0010006C.nw.xml" tokenization="tokenization_parameters" grammar="none" raw_text_char_length="6004" raw_text_md5="2e9949f9b97db97ac7133fd0d6a02f62">
<TEXT>
<SEG id="segment-0" start_char="0" end_char="37">
<ORIGINAL_TEXT>&lt;?xml version="1.0" encoding="utf-8"?&gt;</ORIGINAL_TEXT>
<TOKEN id="token-0-0" pos="unknown" morph="none" start_char="0" end_char="4">&lt;?xml</TOKEN>
<TOKEN id="token-0-1" pos="unknown" morph="none" start_char="6" end_char="18">version="1.0"</TOKEN>
<TOKEN id="token-0-2" pos="unknown" morph="none" start_char="20" end_char="37">encoding="utf-8"?&gt;</TOKEN>
</SEG>
<SEG id="segment-1" start_char="39" end_char="81">
<ORIGINAL_TEXT>&lt;DOC id="ENG_NW_001424_20150208_F0010006C"&gt;</ORIGINAL_TEXT>
<TOKEN id="token-1-0" pos="unknown" morph="none" start_char="39" end_char="42">&lt;DOC</TOKEN>
<TOKEN id="token-1-1" pos="unknown" morph="none" start_char="44" end_char="81">id="ENG_NW_001424_20150208_F0010006C"&gt;</TOKEN>
</SEG>
<SEG id="segment-2" start_char="83" end_char="179">
<ORIGINAL_TEXT>&lt;SOURCE&gt;http://www.stanforddaily.com/2015/02/08/brinksmanship-in-greece-debt-crisis-101/&lt;/SOURCE&gt;</ORIGINAL_TEXT>
<TOKEN id="token-2-0" pos="unknown" morph="none" start_char="83" end_char="179">&lt;SOURCE&gt;http://www.stanforddaily.com/2015/02/08/brinksmanship-in-greece-debt-crisis-101/&lt;/SOURCE&gt;</TOKEN>
</SEG>
<SEG id="segment-3" start_char="181" end_char="222">
<ORIGINAL_TEXT>&lt;DATE_TIME&gt;2015-02-08T00:00:00&lt;/DATE_TIME&gt;</ORIGINAL_TEXT>
<TOKEN id="token-3-0" pos="unknown" morph="none" start_char="181" end_char="222">&lt;DATE_TIME&gt;2015-02-08T00:00:00&lt;/DATE_TIME&gt;</TOKEN>
</SEG>
<SEG id="segment-4" start_char="224" end_char="233">
<ORIGINAL_TEXT>&lt;HEADLINE&gt;</ORIGINAL_TEXT>
<TOKEN id="token-4-0" pos="unknown" morph="none" start_char="224" end_char="233">&lt;HEADLINE&gt;</TOKEN>
</SEG>
<SEG id="segment-5" start_char="235" end_char="274">
<ORIGINAL_TEXT>Brinksmanship in Greece: Debt Crisis 101</ORIGINAL_TEXT>
<TOKEN id="token-5-0" pos="word" morph="none" start_char="235" end_char="247">Brinksmanship</TOKEN>
<TOKEN id="token-5-1" pos="word" morph="none" start_char="249" end_char="250">in</TOKEN>
<TOKEN id="token-5-2" pos="word" morph="none" start_char="252" end_char="257">Greece</TOKEN>
<TOKEN id="token-5-3" pos="punct" morph="none" start_char="258" end_char="258">:</TOKEN>
<TOKEN id="token-5-4" pos="word" morph="none" start_char="260" end_char="263">Debt</TOKEN>
<TOKEN id="token-5-5" pos="word" morph="none" start_char="265" end_char="270">Crisis</TOKEN>
<TOKEN id="token-5-6" pos="number" morph="none" start_char="272" end_char="274">101</TOKEN>
</SEG>
<SEG id="segment-6" start_char="276" end_char="286">
<ORIGINAL_TEXT>&lt;/HEADLINE&gt;</ORIGINAL_TEXT>
<TOKEN id="token-6-0" pos="unknown" morph="none" start_char="276" end_char="286">&lt;/HEADLINE&gt;</TOKEN>
</SEG>
<SEG id="segment-7" start_char="288" end_char="293">
<ORIGINAL_TEXT>&lt;TEXT&gt;</ORIGINAL_TEXT>
<TOKEN id="token-7-0" pos="unknown" morph="none" start_char="288" end_char="293">&lt;TEXT&gt;</TOKEN>
</SEG>
<SEG id="segment-8" start_char="295" end_char="297">
<ORIGINAL_TEXT>&lt;P&gt;</ORIGINAL_TEXT>
<TOKEN id="token-8-0" pos="unknown" morph="none" start_char="295" end_char="297">&lt;P&gt;</TOKEN>
</SEG>
<SEG id="segment-9" start_char="299" end_char="329">
<ORIGINAL_TEXT>The clock is ticking on Greece.</ORIGINAL_TEXT>
<TOKEN id="token-9-0" pos="word" morph="none" start_char="299" end_char="301">The</TOKEN>
<TOKEN id="token-9-1" pos="word" morph="none" start_char="303" end_char="307">clock</TOKEN>
<TOKEN id="token-9-2" pos="word" morph="none" start_char="309" end_char="310">is</TOKEN>
<TOKEN id="token-9-3" pos="word" morph="none" start_char="312" end_char="318">ticking</TOKEN>
<TOKEN id="token-9-4" pos="word" morph="none" start_char="320" end_char="321">on</TOKEN>
<TOKEN id="token-9-5" pos="word" morph="none" start_char="323" end_char="328">Greece</TOKEN>
<TOKEN id="token-9-6" pos="punct" morph="none" start_char="329" end_char="329">.</TOKEN>
</SEG>
<SEG id="segment-10" start_char="331" end_char="334">
<ORIGINAL_TEXT>&lt;/P&gt;</ORIGINAL_TEXT>
<TOKEN id="token-10-0" pos="unknown" morph="none" start_char="331" end_char="334">&lt;/P&gt;</TOKEN>
</SEG>
<SEG id="segment-11" start_char="336" end_char="338">
<ORIGINAL_TEXT>&lt;P&gt;</ORIGINAL_TEXT>
<TOKEN id="token-11-0" pos="unknown" morph="none" start_char="336" end_char="338">&lt;P&gt;</TOKEN>
</SEG>
<SEG id="segment-12" start_char="340" end_char="415">
<ORIGINAL_TEXT>There’s not much time left until Greece will be unable to pay its bills, and</ORIGINAL_TEXT>
<TOKEN id="token-12-0" pos="word" morph="none" start_char="340" end_char="344">There</TOKEN>
<TOKEN id="token-12-1" pos="punct" morph="none" start_char="345" end_char="345">’</TOKEN>
<TOKEN id="token-12-2" pos="word" morph="none" start_char="346" end_char="346">s</TOKEN>
<TOKEN id="token-12-3" pos="word" morph="none" start_char="348" end_char="350">not</TOKEN>
<TOKEN id="token-12-4" pos="word" morph="none" start_char="352" end_char="355">much</TOKEN>
<TOKEN id="token-12-5" pos="word" morph="none" start_char="357" end_char="360">time</TOKEN>
<TOKEN id="token-12-6" pos="word" morph="none" start_char="362" end_char="365">left</TOKEN>
<TOKEN id="token-12-7" pos="word" morph="none" start_char="367" end_char="371">until</TOKEN>
<TOKEN id="token-12-8" pos="word" morph="none" start_char="373" end_char="378">Greece</TOKEN>
<TOKEN id="token-12-9" pos="word" morph="none" start_char="380" end_char="383">will</TOKEN>
<TOKEN id="token-12-10" pos="word" morph="none" start_char="385" end_char="386">be</TOKEN>
<TOKEN id="token-12-11" pos="word" morph="none" start_char="388" end_char="393">unable</TOKEN>
<TOKEN id="token-12-12" pos="word" morph="none" start_char="395" end_char="396">to</TOKEN>
<TOKEN id="token-12-13" pos="word" morph="none" start_char="398" end_char="400">pay</TOKEN>
<TOKEN id="token-12-14" pos="word" morph="none" start_char="402" end_char="404">its</TOKEN>
<TOKEN id="token-12-15" pos="word" morph="none" start_char="406" end_char="410">bills</TOKEN>
<TOKEN id="token-12-16" pos="punct" morph="none" start_char="411" end_char="411">,</TOKEN>
<TOKEN id="token-12-17" pos="word" morph="none" start_char="413" end_char="415">and</TOKEN>
</SEG>
<SEG id="segment-13" start_char="417" end_char="492">
<ORIGINAL_TEXT>yet the two sides of the struggle – the European financial institutions that</ORIGINAL_TEXT>
<TOKEN id="token-13-0" pos="word" morph="none" start_char="417" end_char="419">yet</TOKEN>
<TOKEN id="token-13-1" pos="word" morph="none" start_char="421" end_char="423">the</TOKEN>
<TOKEN id="token-13-2" pos="word" morph="none" start_char="425" end_char="427">two</TOKEN>
<TOKEN id="token-13-3" pos="word" morph="none" start_char="429" end_char="433">sides</TOKEN>
<TOKEN id="token-13-4" pos="word" morph="none" start_char="435" end_char="436">of</TOKEN>
<TOKEN id="token-13-5" pos="word" morph="none" start_char="438" end_char="440">the</TOKEN>
<TOKEN id="token-13-6" pos="word" morph="none" start_char="442" end_char="449">struggle</TOKEN>
<TOKEN id="token-13-7" pos="unknown" morph="none" start_char="451" end_char="451">–</TOKEN>
<TOKEN id="token-13-8" pos="word" morph="none" start_char="453" end_char="455">the</TOKEN>
<TOKEN id="token-13-9" pos="word" morph="none" start_char="457" end_char="464">European</TOKEN>
<TOKEN id="token-13-10" pos="word" morph="none" start_char="466" end_char="474">financial</TOKEN>
<TOKEN id="token-13-11" pos="word" morph="none" start_char="476" end_char="487">institutions</TOKEN>
<TOKEN id="token-13-12" pos="word" morph="none" start_char="489" end_char="492">that</TOKEN>
</SEG>
<SEG id="segment-14" start_char="494" end_char="567">
<ORIGINAL_TEXT>own Greece’s debt and the newly elected Syriza political party  that wants</ORIGINAL_TEXT>
<TOKEN id="token-14-0" pos="word" morph="none" start_char="494" end_char="496">own</TOKEN>
<TOKEN id="token-14-1" pos="word" morph="none" start_char="498" end_char="503">Greece</TOKEN>
<TOKEN id="token-14-2" pos="punct" morph="none" start_char="504" end_char="504">’</TOKEN>
<TOKEN id="token-14-3" pos="word" morph="none" start_char="505" end_char="505">s</TOKEN>
<TOKEN id="token-14-4" pos="word" morph="none" start_char="507" end_char="510">debt</TOKEN>
<TOKEN id="token-14-5" pos="word" morph="none" start_char="512" end_char="514">and</TOKEN>
<TOKEN id="token-14-6" pos="word" morph="none" start_char="516" end_char="518">the</TOKEN>
<TOKEN id="token-14-7" pos="word" morph="none" start_char="520" end_char="524">newly</TOKEN>
<TOKEN id="token-14-8" pos="word" morph="none" start_char="526" end_char="532">elected</TOKEN>
<TOKEN id="token-14-9" pos="word" morph="none" start_char="534" end_char="539">Syriza</TOKEN>
<TOKEN id="token-14-10" pos="word" morph="none" start_char="541" end_char="549">political</TOKEN>
<TOKEN id="token-14-11" pos="word" morph="none" start_char="551" end_char="555">party</TOKEN>
<TOKEN id="token-14-12" pos="word" morph="none" start_char="558" end_char="561">that</TOKEN>
<TOKEN id="token-14-13" pos="word" morph="none" start_char="563" end_char="567">wants</TOKEN>
</SEG>
<SEG id="segment-15" start_char="569" end_char="647">
<ORIGINAL_TEXT>forgiveness for some of that debt – are content to play chicken with each other</ORIGINAL_TEXT>
<TOKEN id="token-15-0" pos="word" morph="none" start_char="569" end_char="579">forgiveness</TOKEN>
<TOKEN id="token-15-1" pos="word" morph="none" start_char="581" end_char="583">for</TOKEN>
<TOKEN id="token-15-2" pos="word" morph="none" start_char="585" end_char="588">some</TOKEN>
<TOKEN id="token-15-3" pos="word" morph="none" start_char="590" end_char="591">of</TOKEN>
<TOKEN id="token-15-4" pos="word" morph="none" start_char="593" end_char="596">that</TOKEN>
<TOKEN id="token-15-5" pos="word" morph="none" start_char="598" end_char="601">debt</TOKEN>
